pf6000t = ["nan",
           "CRx",
           "Dev CR1",
           "Dev CR1 R2",
           "Dev CR2 R4",
           "Temp CR3 R10"]

pf755t_rev_1 = ["nan",
                "CRx",
                "Dev CR1",
                "Dev CR1 R2",
                "Dev CR2 R4",
                "Temp CR3 R10",
                "CR1 R2",
                "CR1 R3",
                "CR2 R4",
                "Dev CR2 R4",
                "CR2 R5",
                "CR2 R6",
                "CR2 R6.003",
                "CR2 R6.004",
                "CR3",
                "CR3 LC",
                "Temp CR3 R10",
                "CR3 R10",
                "CR3 R11",
                "MV_CR1",
                "MV_CR2"]

pf755t_rev_2 = ["nan",
                "CRx",
                "Dev CR1",
                "Dev CR1 R2",
                "Dev CR2 R4",
                "Temp CR3 R10",
                "CR1 R3",
                "CR2 R4",
                "Dev CR2 R4",
                "CR2 R5",
                "CR2 R6",
                "CR2 R6.003",
                "CR2 R6.004",
                "CR3",
                "CR3 LC",
                "Temp CR3 R10",
                "CR3 R10",
                "CR3 R11",
                "MV_CR1",
                "MV_CR2"]

pf755t_rev_3 = ["nan",
                "CRx",
                "Dev CR1",
                "Dev CR1 R2",
                "Dev CR2 R4",
                "Temp CR3 R10",
                "CR2 R4",
                "Dev CR2 R4",
                "CR2 R5",
                "CR2 R6",
                "CR2 R6.003",
                "CR2 R6.004",
                "CR3",
                "CR3 LC",
                "Temp CR3 R10",
                "CR3 R10",
                "CR3 R11",
                "MV_CR1",
                "MV_CR2"]

pf755t_rev_4 = ["nan",
                "CRx",
                "Dev CR1",
                "Dev CR1 R2",
                "Dev CR2 R4",
                "Temp CR3 R10",
                "CR2 R5",
                "CR2 R6",
                "CR2 R6.003",
                "CR2 R6.004",
                "CR3",
                "CR3 LC",
                "Temp CR3 R10",
                "CR3 R10",
                "CR3 R11",
                "MV_CR1",
                "MV_CR2"]

pf755t_rev_5 = ["nan",
                "CRx",
                "Dev CR1",
                "Dev CR1 R2",
                "Dev CR2 R4",
                "Temp CR3 R10",
                "CR2 R5",
                "CR2 R6",
                "CR2 R6.003",
                "CR2 R6.004",
                "CR3",
                "CR3 LC",
                "Temp CR3 R10",
                "CR3 R10",
                "CR3 R11",
                "MV_CR1",
                "MV_CR2"]

pf755t_rev_6_3 = ["nan",
                  "CRx",
                  "Dev CR1",
                  "Dev CR1 R2",
                  "Dev CR2 R4",
                  "Temp CR3 R10",
                  "CR2 R6.004",
                  "CR3",
                  "CR3 LC",
                  "Temp CR3 R10",
                  "CR3 R10",
                  "CR3 R11",
                  "MV_CR1",
                  "MV_CR2"]

pf755t_rev_6_4 = ["nan",
                  "CRx",
                  "Dev CR1",
                  "Dev CR1 R2",
                  "Dev CR2 R4",
                  "Temp CR3 R10",
                  "CR3",
                  "CR3 LC",
                  "Temp CR3 R10",
                  "CR3 R10",
                  "CR3 R11",
                  "MV_CR1",
                  "MV_CR2"]

pf755t_rev_7 = ["nan",
                "CRx",
                "Dev CR1",
                "Dev CR1 R2",
                "Dev CR2 R4",
                "Temp CR3 R10",
                "CR3 R10",
                "CR3 R11",
                "MV_CR1",
                "MV_CR2"]

pf755t_rev_8 = ["nan",
                "CRx",
                "Dev CR1",
                "Dev CR1 R2",
                "Dev CR2 R4",
                "Temp CR3 R10",
                "CR3 R10",
                "CR3 R11",
                "MV_CR1",
                "MV_CR2"]

pf755t_rev_10 = ["nan",
                 "CRx",
                 "Dev CR1",
                 "Dev CR1 R2",
                 "Dev CR2 R4",
                 "Temp CR3 R10",
                 "CR3 R11",
                 "MV_CR1",
                 "MV_CR2"]

pf755t_rev_11 = ["nan",
                 "CRx",
                 "Dev CR1",
                 "Dev CR1 R2",
                 "Dev CR2 R4",
                 "Temp CR3 R10",
                 "MV_CR1",
                 "MV_CR2"]
